//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddProduct
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<long> price { get; set; }
        public string imageUrl { get; set; }
    }
}
